// astros_vue/src/components/modules/uart/UartModule.vue
<script setup lang="ts">
import { computed, type PropType, type Component } from 'vue';
import { ModuleType, ModuleSubType } from '@/models/enums';
import type { UartModule } from '@/models/module.types';
import type { RemoveModuleEvent, ServoTestEvent } from '@/models/events';
import GenericSerialModule from './submodules/GenericSerialModule.vue';
import KangarooModule from './submodules/KangarooModule.vue';
import HcrSerialModule from './submodules/HcrSerialModule.vue';
import MaestroModule from './submodules/MaestroModule.vue';

// Props
const props = defineProps({
    module: {
        type: Object as PropType<UartModule>,
        required: true
    },
    parentTestId: {
        type: String,
        required: true
    },
    isMaster: {
        type: Boolean,
        default: false
    }
});

// Emits
const emit = defineEmits<{
    removeModule: [event: RemoveModuleEvent];
    servoTest: [event: ServoTestEvent];
}>();

// Computed properties
const subtypeName = computed(() => {
    switch (props.module.moduleSubType) {
        case ModuleSubType.genericSerial:
            return 'Generic Serial';
        case ModuleSubType.kangaroo:
            return 'Kangaroo X2';
        case ModuleSubType.humanCyborgRelationsSerial:
            return 'HCR';
        case ModuleSubType.maestro:
            return 'Pololu Maestro';
        default:
            return '';
    }
});

const subModuleComponent = computed<Component | null>(() => {
    switch (props.module.moduleSubType) {
        case ModuleSubType.genericSerial:
            return GenericSerialModule;
        case ModuleSubType.kangaroo:
            return KangarooModule;
        case ModuleSubType.humanCyborgRelationsSerial:
            return HcrSerialModule;
        case ModuleSubType.maestro:
            return MaestroModule;
        default:
            return null;
    }
});

// Methods
const nameClicked = (evt: MouseEvent) => {
    evt.stopPropagation();
};

const removeModule = (event: Event) => {
    event.stopPropagation();
    emit('removeModule', {
        locationId: props.module.locationId,
        id: props.module.id,
        module: ModuleType.uart,
    });
};

const onServoTestEvent = (evt: ServoTestEvent) => {
    emit('servoTest', evt);
};
</script>

<template>
    <div class="collapse collapse-arrow bg-base-100 border border-base-300">
        <input type="checkbox" class="peer" />
        <div :data-testid="`${parentTestId}-serial-${module.moduleSubType}-header`"
            class="collapse-title flex items-center justify-between pr-12">
            <div class="flex-shrink-0 min-w-0">
                <input :data-testid="`${parentTestId}-serial-${module.moduleSubType}-name`" v-model="module.name"
                    @click="nameClicked" @keydown.space.stop placeholder="Name"
                    class="input input-bordered input-sm w-full max-w-xs" />
            </div>
            <div class="flex items-center gap-2 ml-4">
                <p class="text-sm text-base-content/60">{{ subtypeName }}</p>
                <button @click.stop="removeModule" @keydown.enter.prevent="removeModule"
                    @keydown.space.prevent="removeModule" class="btn btn-sm btn-circle btn-ghost">
                    <span class="text-lg">×</span>
                </button>
            </div>
        </div>
        <div class="collapse-content">
            <div v-if="!subModuleComponent" class="p-4 bg-base-200 rounded border border-dashed border-base-300">
                <p class="text-sm text-base-content/60 italic">
                    UART Sub-module content ({{ subtypeName }}) - Channel: {{ module.uartChannel }}, Baud: {{
                        module.baudRate }}
                </p>
                <!-- Sub-modules will be added here:
                - GenericSerialModule
                - KangarooModule
                - HcrSerialModule
                - MaestroModule
                -->
            </div>
            <component v-else :is="subModuleComponent" :module="module" :parent-test-id="parentTestId"
                :is-master="isMaster" @servo-test-event="onServoTestEvent" />
        </div>
    </div>
</template>

<style scoped>
/* Using Tailwind and DaisyUI utilities */
</style>

// astros_client/src/app/components/esp-module/uart/uart-module/uart-module.component.ts
import {
  AfterContentInit,
  AfterViewInit,
  Component,
  ComponentRef,
  EventEmitter,
  Input,
  Output,
  ViewChild,
  ViewContainerRef,
} from '@angular/core';
import {
  MatExpansionPanel,
  MatExpansionPanelDescription,
  MatExpansionPanelHeader,
  MatExpansionPanelTitle,
} from '@angular/material/expansion';
import { ModuleType, ModuleSubType, UartModule } from 'astros-common';
import { GenericSerialModuleComponent } from '../uart-submodules/generic-serial-module/generic-serial-module.component';
import { KangarooModuleComponent } from '../uart-submodules/kangaroo-module/kangaroo-module.component';
import { MaestroModuleComponent } from '../uart-submodules/maestro-module/maestro-module.component';
import { FormsModule } from '@angular/forms';
import { BaseUartSubModuleComponent } from '../uart-submodules/base-uart-sub-module/base-uart-sub-module.component';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import { faTimes } from '@fortawesome/free-solid-svg-icons';
import { RemoveModuleEvent, ServoTestEvent } from '../../utility/module-events';
import { HcrSerialModuleComponent } from '../uart-submodules/hcr-serial-module/hcr-serial-module.component';

@Component({
  selector: 'app-uart-module',
  templateUrl: './uart-module.component.html',
  styleUrl: './uart-module.component.scss',
  imports: [
    MatExpansionPanel,
    MatExpansionPanelHeader,
    MatExpansionPanelTitle,
    MatExpansionPanelDescription,
    FormsModule,
    FontAwesomeModule,
  ],
})
export class UartModuleComponent implements AfterViewInit, AfterContentInit {
  @ViewChild('uartContainer', { read: ViewContainerRef })
  uartContainer!: ViewContainerRef;

  @Input()
  isMaster = false;

  @Input()
  module!: UartModule;

  @Input()
  parentTestId!: string;

  @Output()
  removeModuleEvent = new EventEmitter<RemoveModuleEvent>();

  @Output()
  servoTestEvent = new EventEmitter<ServoTestEvent>();

  subtypeName = '';
  removeIcon = faTimes;
  component!: ComponentRef<unknown>;

  nameClicked(evt: MouseEvent) {
    evt.stopPropagation();
  }

  ngAfterViewInit(): void {
    this.setModule();
  }

  ngAfterContentInit(): void {
    switch (this.module.moduleSubType) {
      case ModuleSubType.genericSerial:
        this.subtypeName = 'Generic Serial';
        break;
      case ModuleSubType.kangaroo:
        this.subtypeName = 'Kangaroo X2';
        break;
      case ModuleSubType.humanCyborgRelationsSerial:
        this.subtypeName = 'HCR';
        break;
      case ModuleSubType.maestro:
        this.subtypeName = 'Pololu Maestro';
        break;
      default:
        break;
    }
  }

  setModule() {
    this.uartContainer?.clear();

    let component!: ComponentRef<BaseUartSubModuleComponent>;

    switch (this.module.moduleSubType) {
      case ModuleSubType.humanCyborgRelationsSerial:
        component = this.uartContainer.createComponent(
          HcrSerialModuleComponent,
        ) as ComponentRef<HcrSerialModuleComponent>;
        break;
      case ModuleSubType.genericSerial:
        component = this.uartContainer.createComponent(
          GenericSerialModuleComponent,
        ) as ComponentRef<GenericSerialModuleComponent>;
        break;
      case ModuleSubType.kangaroo:
        component = this.uartContainer.createComponent(
          KangarooModuleComponent,
        ) as ComponentRef<KangarooModuleComponent>;
        break;
      case ModuleSubType.maestro:
        {
          component = this.uartContainer.createComponent(
            MaestroModuleComponent,
          ) as ComponentRef<MaestroModuleComponent>;

          component.instance.servoTestEvent.subscribe(
            (evt: ServoTestEvent) => {this.onServoTestEvent(evt);})
          break;
        }
      default:
        break;
    }

    if (component) {
      component.instance.parentTestId = this.parentTestId;
      component.instance.module = this.module;
      component.instance.isMaster = this.isMaster;
    }
  }

  removeModule(event: Event) {
    event.stopPropagation();
    this.removeModuleEvent.emit({
      locationId: this.module.locationId,
      id: this.module.id,
      module: ModuleType.uart,
    });
  }

  onServoTestEvent(evt: ServoTestEvent): void {
    this.servoTestEvent.emit(evt);
  }
}

<mat-expansion-panel>
    <mat-expansion-panel-header [attr.data-testId]="parentTestId + '-serial-' + module.moduleSubType +'-header'">
        <mat-panel-title>
            <div class="header-name">
                <input 
                    matInput 
                    placeholder="Name" 
                    [(ngModel)]="module.name"
                    (keydown.space)="$event.stopImmediatePropagation()"  
                    (click)="nameClicked($event)" 
                />
            </div>
        </mat-panel-title>
        <mat-panel-description>
            <div class="header-box">
                <div class="header-spacer"></div>
                <div>
                    <p  id="subtype-name">{{ subtypeName }}</p>
                </div>
                <div class="header-button">
                    <button
                        (keydown.enter)="$event.preventDefault();removeModule($event);"
                        (keydown.space)="$event.preventDefault();removeModule($event);"  
                        (click)="removeModule($event)">
                        <fa-icon [icon]="removeIcon"/>
                    </button>
                </div>
            </div>
        </mat-panel-description>
    </mat-expansion-panel-header>
    <ng-template #uartContainer></ng-template>
</mat-expansion-panel>
