// astros_client/src/app/components/esp-module/i2c/i2c-module/i2c-module.component.ts
import {
  AfterContentInit,
  AfterViewInit,
  Component,
  ComponentRef,
  EventEmitter,
  Input,
  Output,
  ViewChild,
  ViewContainerRef,
} from '@angular/core';
import { FormsModule } from '@angular/forms';
import {
  MatExpansionPanel,
  MatExpansionPanelDescription,
  MatExpansionPanelHeader,
  MatExpansionPanelTitle,
} from '@angular/material/expansion';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import { faTimes } from '@fortawesome/free-solid-svg-icons';
import { I2cModule, ModuleType, ModuleSubType } from 'astros-common';
import { RemoveModuleEvent } from '../../utility/module-events';
import { GenericI2cModuleComponent } from '../i2c-submodules/generic-i2c-module/generic-i2c-module.component';
import { Pca9685ModuleComponent } from '../i2c-submodules/pca9685-module/pca9685-module.component';
import { BaseI2cSubModuleComponent } from '../i2c-submodules/base-i2c-sub-module/base-i2c-sub-module.component';

export interface AddressChangeEvent {
  old: number;
  new: number;
}

@Component({
  selector: 'app-i2c-module',
  imports: [
    MatExpansionPanel,
    MatExpansionPanelHeader,
    MatExpansionPanelTitle,
    MatExpansionPanelDescription,
    FormsModule,
    FontAwesomeModule,
  ],
  templateUrl: './i2c-module.component.html',
  styleUrl: './i2c-module.component.scss',
})
export class I2cModuleComponent implements AfterViewInit, AfterContentInit {
  @ViewChild('i2cContainer', { read: ViewContainerRef })
  i2cContainer!: ViewContainerRef;

  @Input()
  module!: I2cModule;

  // here to trigger change detection for object property changes
  @Input()
  set updateTrigger(val: number) {
    console.log('I2C Module Update Trigger: ', val);
    this.setModule();
  }

  @Output()
  removeModuleEvent = new EventEmitter<RemoveModuleEvent>();

  @Output()
  i2cAddressChangedEvent = new EventEmitter<AddressChangeEvent>();

  subtypeName = '';
  removeIcon = faTimes;
  component!: ComponentRef<unknown>;

  nameClicked(evt: MouseEvent) {
    evt.stopPropagation();
  }

  ngAfterViewInit(): void {
    this.setModule();
  }

  ngAfterContentInit(): void {
    switch (this.module.moduleSubType) {
      case ModuleSubType.genericI2C:
        this.subtypeName = 'Generic I2C';
        break;
      case ModuleSubType.humanCyborgRelationsI2C:
        this.subtypeName = 'Human Cyborg Relations';
        break;
      case ModuleSubType.pwmBoard:
        this.subtypeName = 'PCA9685 PWM Board';
        break;
      default:
        break;
    }
  }

  setModule() {
    this.i2cContainer?.clear();

    let component!: ComponentRef<BaseI2cSubModuleComponent>;

    switch (this.module.moduleSubType) {
      case ModuleSubType.genericI2C:
        component = this.i2cContainer.createComponent(
          GenericI2cModuleComponent,
        ) as ComponentRef<GenericI2cModuleComponent>;
        break;
      case ModuleSubType.humanCyborgRelationsI2C:
      case ModuleSubType.pwmBoard:
        component = this.i2cContainer.createComponent(
          Pca9685ModuleComponent,
        ) as ComponentRef<Pca9685ModuleComponent>;
        break;
      default:
        break;
    }

    if (component) {
      component.instance.module = this.module;
      component.instance.i2cAddressChangedEvent.subscribe((val: string) => {
        console.log('I2C Address Changed: ', val);

        this.i2cAddressChangedEvent.emit({
          old: this.module.i2cAddress,
          new: parseInt(val, 10),
        });
      });
    }
  }

  removeModule(event: Event) {
    event.stopPropagation();
    this.removeModuleEvent.emit({
      locationId: this.module.locationId,
      id: this.module.id,
      module: ModuleType.i2c,
    });
  }
}

<mat-expansion-panel>
    <mat-expansion-panel-header [attr.data-testId]="parentTestId + '-i2c-' + module.moduleSubType +'-header'">
        <mat-panel-title>
            <div class="header-name">
                <input 
                    [attr.data-testId]="parentTestId + '-i2c-' + module.moduleSubType +'-name'"
                    matInput 
                    placeholder="Name" 
                    [(ngModel)]="module.name" 
                    (keydown.space)="$event.stopImmediatePropagation()"
                    (click)="nameClicked($event)" 
                />
            </div>
        </mat-panel-title>
        <mat-panel-description>
            <div class="header-box">
                <div class="header-spacer"></div>
                <div>
                    <p id="subtype-name" >{{ subtypeName }}</p>
                </div>
                <div class="header-button">
                    <button
                        (keydown.enter)="$event.preventDefault();removeModule($event);" 
                        (keydown.space)="$event.preventDefault();removeModule($event);"
                        (click)="removeModule($event)">
                        <fa-icon [icon]="removeIcon"/>
                    </button>
                </div>
            </div>
        </mat-panel-description>
    </mat-expansion-panel-header>
    <ng-template #i2cContainer></ng-template>
</mat-expansion-panel>

// astros_vue/src/components/modules/i2c/I2cModule.vue
<script setup lang="ts">
import { computed, type PropType, type Component } from 'vue';
import { ModuleType, ModuleSubType } from '@/models/enums';
import type { I2cModule } from '@/models/module.types';
import type { RemoveModuleEvent, AddressChangeEvent } from '@/models/events';
import GenericI2cModule from './submodules/GenericI2cModule.vue';
import Pca9685Module from './submodules/Pca9685Module.vue';

// Props
const props = defineProps({
    module: {
        type: Object as PropType<I2cModule>,
        required: true
    },
    parentTestId: {
        type: String,
        required: true
    },
    updateTrigger: {
        type: Number,
        default: 0
    }
});

// Emits
const emit = defineEmits<{
    removeModule: [event: RemoveModuleEvent];
    i2cAddressChanged: [event: AddressChangeEvent];
}>();

// Computed properties
const subtypeName = computed(() => {
    switch (props.module.moduleSubType) {
        case ModuleSubType.genericI2C:
            return 'Generic I2C';
        case ModuleSubType.humanCyborgRelationsI2C:
            return 'Human Cyborg Relations';
        case ModuleSubType.pwmBoard:
            return 'PCA9685 PWM Board';
        default:
            return '';
    }
});

const subModuleComponent = computed<Component | null>(() => {
    switch (props.module.moduleSubType) {
        case ModuleSubType.genericI2C:
            return GenericI2cModule;
        case ModuleSubType.humanCyborgRelationsI2C:
        case ModuleSubType.pwmBoard:
            return Pca9685Module;
        default:
            return null;
    }
});

// Methods
const nameClicked = (evt: MouseEvent) => {
    evt.stopPropagation();
};

const removeModule = (event: Event) => {
    event.stopPropagation();
    emit('removeModule', {
        locationId: props.module.locationId,
        id: props.module.id,
        module: ModuleType.i2c,
    });
};

const onI2cAddressChanged = (value: string) => {
    console.log('I2C Address Changed:', value);
    emit('i2cAddressChanged', {
        old: props.module.i2cAddress,
        new: parseInt(value, 10),
    });
};
</script>

<template>
    <div class="collapse collapse-arrow bg-base-100 border border-base-300">
        <input type="checkbox" class="peer" />
        <div :data-testid="`${parentTestId}-i2c-${module.moduleSubType}-header`"
            class="collapse-title flex items-center justify-between pr-12">
            <div class="flex-shrink-0 min-w-0">
                <input :data-testid="`${parentTestId}-i2c-${module.moduleSubType}-name`" v-model="module.name"
                    @click="nameClicked" @keydown.space.stop placeholder="Name"
                    class="input input-bordered input-sm w-full max-w-xs" />
            </div>
            <div class="flex items-center gap-2 ml-4">
                <p class="text-sm text-base-content/60">{{ subtypeName }}</p>
                <button @click.stop="removeModule" @keydown.enter.prevent="removeModule"
                    @keydown.space.prevent="removeModule" class="btn btn-sm btn-circle btn-ghost">
                    <span class="text-lg">×</span>
                </button>
            </div>
        </div>
        <div class="collapse-content">
            <component 
                v-if="subModuleComponent"
                :is="subModuleComponent"
                :module="module"
                :parent-test-id="parentTestId"
                @i2c-address-changed="onI2cAddressChanged"
            />
        </div>
    </div>
</template>

<style scoped>
/* Using Tailwind and DaisyUI utilities */
</style>
