// astros_vue/src/components/modules/uart/submodules/MaestroChannel.vue
<script setup lang="ts">
import { computed, type PropType } from 'vue';
import ServoSettings from '../../shared/ServoSettings.vue';
import { ModuleSubType } from '@/models/enums';
import type { ServoTestEvent } from '@/models/events';

// MaestroChannel interface
interface MaestroChannel {
    id: string;
    channelNumber: number;
    enabled: boolean;
    channelName: string;
    isServo: boolean;
    inverted: boolean;
    minPos: number;
    maxPos: number;
    homePos: number;
}

// Props
const props = defineProps({
    channel: {
        type: Object as PropType<MaestroChannel>,
        required: true
    },
    parentTestId: {
        type: String,
        required: true
    }
});

// Emits
const emit = defineEmits<{
    servoTest: [event: ServoTestEvent];
}>();

// Computed
const type = computed({
    get: () => {
        if (!props.channel.enabled) return '0';
        return props.channel.isServo ? '1' : '2';
    },
    set: (val: string) => {
        switch (val) {
            case '0':
                props.channel.enabled = false;
                break;
            case '1':
                props.channel.enabled = true;
                props.channel.isServo = true;
                break;
            case '2':
                props.channel.enabled = true;
                props.channel.isServo = false;
                break;
        }
    }
});

// Methods
const testServoModal = () => {
    emit('servoTest', {
        controllerAddress: '',
        controllerName: '',
        moduleSubType: ModuleSubType.maestro,
        channelNumber: props.channel.channelNumber,
    });
};
</script>

<template>
    <div class="space-y-2">
        <div class="flex items-center gap-4 flex-wrap">
            <div class="font-medium min-w-20">Channel {{ channel.channelNumber }}</div>
            <select :data-testid="`${parentTestId}-maestro-ch-${channel.channelNumber}-type`" v-model="type"
                class="select select-bordered select-sm w-30">
                <option value="0">Disabled</option>
                <option value="1">Servo</option>
                <option value="2">Output</option>
            </select>
            <div class="grow"></div>
            <button @click="testServoModal" class="btn btn-sm btn-outline">Test</button>
        </div>
        <div v-if="channel">
            <ServoSettings :test-id="`${parentTestId}-maestro-ch-${channel.channelNumber}`" :enabled="channel.enabled"
                v-model:name="channel.channelName" :is-servo="channel.isServo" v-model:invert="channel.inverted"
                v-model:min-pulse="channel.minPos" v-model:max-pulse="channel.maxPos"
                v-model:home-position="channel.homePos" />
        </div>
    </div>
</template>

// astros_client/src/app/components/esp-module/uart/uart-submodules/maestro-channel/maestro-channel.component.ts

import {
  AfterContentInit,
  Component,
  EventEmitter,
  Input,
  Output,
} from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ServoSettingsComponent } from '@src/components/esp-module/shared/servo-settings/servo-settings.component';
import { MaestroChannel, ModuleSubType } from 'astros-common';
import { ServoTestEvent } from '../../../utility/module-events';

@Component({
  selector: 'app-maestro-channel',
  imports: [ServoSettingsComponent, FormsModule],
  templateUrl: './maestro-channel.component.html',
  styleUrl: './maestro-channel.component.scss',
})
export class MaestroChannelComponent implements AfterContentInit {
  @Input()
  channel!: MaestroChannel;

  @Input()
  parentTestId!: string;

  @Output()
  servoTestEvent = new EventEmitter<ServoTestEvent>();

  type = '0';

  ngAfterContentInit(): void {
    if (this.channel) {
      if (!this.channel.enabled) {
        this.type = '0';
        return;
      }
      this.type = this.channel.isServo ? '1' : '2';
    }
  }

  onTypeChanged(evt: string): void {
    switch (evt) {
      case '0':
        this.channel.enabled = false;
        break;
      case '1':
        this.channel.enabled = true;
        this.channel.isServo = true;
        break;
      case '2':
        this.channel.enabled = true;
        this.channel.isServo = false;
        break;
    }
  }

  testServoModal(): void {
    this.servoTestEvent.emit({
      controllerAddress: '',
      controllerName: '',
      moduleIdx: -1,
      moduleSubType: ModuleSubType.maestro,
      channelNumber: this.channel.channelNumber,
      value: 0,
    });
  }
}

<div class="maestro-channel">
  <div class="label-row">
    @if (channel) {
      <div class="label">Channel {{channel.channelNumber}}</div>
    }
    <div class="type-select">
      <select
        [attr.data-testId]="parentTestId + '-maestro-ch-' + channel.channelNumber + '-type'"
        [(ngModel)]="type"
        (ngModelChange)="onTypeChanged($event)">
        <option value="0">Disabled</option>
        <option value="1">Servo</option>
        <option value="2">Output</option>
      </select>
    </div>
    <div class="spacer"></div>
    <div class="test-button">
      <button (click)="testServoModal()">Test</button>
    </div>
  </div>
  @if (channel) {
    <div class="servo-settings">
      <app-servo-settings
        [testId]="parentTestId + '-maestro-ch-' + channel.channelNumber"
        [enabled]="channel.enabled"
        [(name)]="channel.channelName"
        [isServo]="channel.isServo"
        [(invert)]="channel.inverted"
        [(minPulse)]="channel.minPos"
        [(maxPulse)]="channel.maxPos"
        [(homePosition)]="channel.homePos" />
      </div>
    }
  </div>
