// astros_vue/src/components/modules/EspModule.vue
<script setup lang="ts">
import { ref, type PropType } from 'vue';
import { ModuleType } from '@/models/enums';
import type { ControllerLocation } from '@/models/module.types';
import type {
    AddModuleEvent,
    RemoveModuleEvent,
    ServoTestEvent,
    AddressChangeEvent
} from '@/models/events';

// Props
const props = defineProps({
    isMaster: {
        type: Boolean,
        default: false
    },
    location: {
        type: Object as PropType<ControllerLocation>,
        required: true
    },
    parentTestId: {
        type: String,
        required: true
    }
});

// Emits
const emit = defineEmits<{
    removeModule: [event: RemoveModuleEvent];
    addModule: [event: AddModuleEvent];
    openServoTestModal: [event: ServoTestEvent];
}>();

// Reactive state
const uartPanelOpenState = ref(false);
const i2cPanelOpenState = ref(false);
const gpioPanelOpenState = ref(false);
const i2cUpdateTrigger = ref(0);

// Methods
const addUartModule = (evt: Event) => {
    evt.stopPropagation();

    if (!uartPanelOpenState.value) {
        uartPanelOpenState.value = true;
    }

    emit('addModule', {
        locationId: props.location.id,
        module: ModuleType.uart,
    });
};

const addI2cModule = (evt: Event) => {
    evt.stopPropagation();

    if (!i2cPanelOpenState.value) {
        i2cPanelOpenState.value = true;
    }

    emit('addModule', {
        locationId: props.location.id,
        module: ModuleType.i2c,
    });
};

const removeModule = (evt: RemoveModuleEvent) => {
    emit('removeModule', {
        locationId: props.location.id,
        id: evt.id,
        module: evt.module,
    });
};

const i2cAddressChanged = (evt: AddressChangeEvent) => {
    // if the new address is in use, swap it to the old address
    const m1 = props.location.i2cModules.find((m) => m.i2cAddress === evt.new);

    if (m1) {
        m1.i2cAddress = evt.old;
    }

    const m2 = props.location.i2cModules.find((m) => m.i2cAddress === evt.old);

    if (m2) {
        m2.i2cAddress = evt.new;
    }

    i2cUpdateTrigger.value++;
};

const onServoTestEvent = (evt: ServoTestEvent) => {
    evt.controllerAddress = props.location.controller.address;
    evt.controllerName = props.location.controller.name;
    emit('openServoTestModal', evt);
};
</script>

<template>
    <div class="w-full space-y-2">
        <!-- Serial Modules Panel -->
        <div class="collapse collapse-arrow bg-base-200 border border-base-300"
            :class="{ 'collapse-open': uartPanelOpenState, 'collapse-close': !uartPanelOpenState }">
            <input type="checkbox" v-model="uartPanelOpenState" class="hidden" />
            <div :data-testid="`${parentTestId}-serial-header`"
                class="collapse-title flex items-center justify-between pr-12 cursor-pointer"
                @click="uartPanelOpenState = !uartPanelOpenState">
                <h3 class="font-medium">Serial Modules</h3>
                <button :data-testid="`${parentTestId}-add-serial`" @click.stop="addUartModule"
                    class="btn btn-sm btn-circle btn-ghost">
                    <span class="text-lg">+</span>
                </button>
            </div>
            <div class="collapse-content">
                <ul v-if="location?.uartModules" class="space-y-2 max-h-96 overflow-y-auto p-0">
                    <li v-for="module in location.uartModules" :key="module.id">
                        <!-- Replace with UartModule component when available -->
                        <div
                            class="p-4 bg-base-100 border border-dashed border-base-300 rounded italic text-base-content/60">
                            UART Module: {{ module.id }}
                            <!-- <UartModule 
                @remove-module-event="removeModule" 
                @servo-test-event="onServoTestEvent"
                :module="module" 
                :is-master="isMaster"
                :parent-test-id="parentTestId"
              /> -->
                        </div>
                    </li>
                </ul>
            </div>
        </div>

        <!-- I2C Configuration Panel -->
        <div class="collapse collapse-arrow bg-base-200 border border-base-300"
            :class="{ 'collapse-open': i2cPanelOpenState, 'collapse-close': !i2cPanelOpenState }">
            <input type="checkbox" v-model="i2cPanelOpenState" class="hidden" />
            <div :data-testid="`${parentTestId}-i2c-header`"
                class="collapse-title flex items-center justify-between pr-12 cursor-pointer"
                @click="i2cPanelOpenState = !i2cPanelOpenState">
                <h3 class="font-medium">I2C configuration</h3>
                <button :data-testid="`${parentTestId}-add-i2c`" @click.stop="addI2cModule"
                    class="btn btn-sm btn-circle btn-ghost">
                    <span class="text-lg">+</span>
                </button>
            </div>
            <div class="collapse-content">
                <ul v-if="location?.i2cModules" class="space-y-2 max-h-96 overflow-y-auto p-0">
                    <li v-for="module in location.i2cModules" :key="module.id">
                        <!-- Replace with I2cModule component when available -->
                        <div class="p-4 bg-base-100 border-2 border-base-content/20 rounded">
                            I2C Module: {{ module.id }}
                            <!-- <I2cModule 
                @remove-module-event="removeModule" 
                @i2c-address-changed-event="i2cAddressChanged"
                :update-trigger="i2cUpdateTrigger"
                :module="module" 
                :parent-test-id="parentTestId"
              /> -->
                        </div>
                    </li>
                </ul>
            </div>
        </div>

        <!-- GPIO Configuration Panel -->
        <div class="collapse collapse-arrow bg-base-200 border border-base-300"
            :class="{ 'collapse-open': gpioPanelOpenState, 'collapse-close': !gpioPanelOpenState }">
            <input type="checkbox" v-model="gpioPanelOpenState" class="hidden" />
            <div :data-testid="`${parentTestId}-gpio-header`" class="collapse-title cursor-pointer"
                @click="gpioPanelOpenState = !gpioPanelOpenState">
                <h3 class="font-medium">GPIO configuration</h3>
            </div>
            <div class="collapse-content">
                <ul v-if="location?.gpioModule" class="space-y-2 max-h-96 overflow-y-auto p-0">
                    <li v-for="channel in location.gpioModule.channels" :key="channel.id">
                        <!-- Replace with GpioChannel component when available -->
                        <div class="p-4 bg-base-100 border-2 border-base-content/20 rounded">
                            GPIO Channel: {{ channel.id }}
                            <!-- <GpioChannel 
                :channel="channel"
                :parent-test-id="parentTestId"
              /> -->
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</template>

<style scoped>
/* Minimal custom styles - using Tailwind and DaisyUI utilities */
</style>

// astros_client/src/app/components/esp-module/esp/esp-module.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import {
  MatExpansionPanel,
  MatAccordion,
  MatExpansionPanelHeader,
  MatExpansionPanelTitle,
  MatExpansionPanelDescription,
} from '@angular/material/expansion';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import { ControllerLocation, ModuleSubType, ModuleType } from 'astros-common';
import { UartModuleComponent } from '../uart/uart-module/uart-module.component';
import { NgIf, NgFor } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { faPlus } from '@fortawesome/free-solid-svg-icons';
import {
  I2cModuleComponent,
  AddressChangeEvent,
} from '../i2c/i2c-module/i2c-module.component';
import {
  AddModuleEvent,
  RemoveModuleEvent,
  ServoTestEvent,
} from '../utility/module-events';
import { GpioChannelComponent } from '../gpio/gpio-channel/gpio-channel.component';

@Component({
  selector: 'app-esp-module',
  templateUrl: './esp-module.component.html',
  styleUrls: ['./esp-module.component.scss'],
  imports: [
    MatAccordion,
    MatExpansionPanel,
    MatExpansionPanelHeader,
    MatExpansionPanelTitle,
    NgIf,
    FormsModule,
    MatExpansionPanelDescription,
    NgFor,
    UartModuleComponent,
    I2cModuleComponent,
    GpioChannelComponent,
    FontAwesomeModule,
  ],
})
export class EspModuleComponent {
  @Output()
  removeModuleEvent = new EventEmitter<RemoveModuleEvent>();

  @Output()
  addModuleEvent = new EventEmitter<AddModuleEvent>();

  @Output()
  openServoTestModal = new EventEmitter<ServoTestEvent>();

  @Input()
  isMaster = false;

  @Input()
  location!: ControllerLocation;

  @Input()
  parentTestId!: string;

  addIcon = faPlus;

  uartPanelOpenState = false;
  i2cPanelOpenState = false;
  i2cUpdateTrigger = 0;

  moduleCallback(_: unknown) {
    throw new Error('Method not implemented.');
  }

  addUartModule(evt: Event) {
    evt.stopPropagation();

    if (!this.uartPanelOpenState) {
      this.uartPanelOpenState = true;
    }

    this.addModuleEvent.emit({
      locationId: this.location.id,
      module: ModuleType.uart,
    });
  }

  addI2cModule(evt: Event) {
    evt.stopPropagation();

    if (!this.i2cPanelOpenState) {
      this.i2cPanelOpenState = true;
    }

    this.addModuleEvent.emit({
      locationId: this.location.id,
      module: ModuleType.i2c,
    });
  }

  removeModule(evt: RemoveModuleEvent) {
    this.removeModuleEvent.emit({
      locationId: this.location.id,
      id: evt.id,
      module: evt.module,
    });
  }

  i2cAddressChanged(evt: AddressChangeEvent) {
    // if the new address in use, swap it to the old address
    const m1 = this.location.i2cModules.find((m) => m.i2cAddress === evt.new);

    if (m1) {
      m1.i2cAddress = evt.old;
    }

    const m2 = this.location.i2cModules.find((m) => m.i2cAddress === evt.old);

    if (m2) {
      m2.i2cAddress = evt.new;
    }

    this.i2cUpdateTrigger++;
  }

  onServoTestEvent(evt: ServoTestEvent) {
    evt.controllerAddress = this.location.controller.address
    evt.controllerName = this.location.controller.name;
    this.openServoTestModal.emit(evt);
  }
}

<mat-accordion>
    <mat-expansion-panel [expanded]="uartPanelOpenState" (closed)="uartPanelOpenState = false">
        <mat-expansion-panel-header [attr.data-testId]="parentTestId + '-serial-header'">
            <mat-panel-title>Serial Modules</mat-panel-title>
            <mat-panel-description>
                <div class="header-box">
                    <div class="header-spacer"></div>
                    <div class="header-button">
                        <button 
                            [attr.data-testId]="parentTestId + '-add-serial'" 
                            (click)="addUartModule($event)"
                            >
                            <fa-icon [icon]="addIcon"/>
                        </button>
                    </div>
                </div>
            </mat-panel-description>
        </mat-expansion-panel-header>
        <ul *ngIf="(location?.uartModules)" class="uart-list">
            <li *ngFor="let module of location.uartModules">
                <app-uart-module 
                    (removeModuleEvent)="removeModule($event)" 
                    (servoTestEvent)="onServoTestEvent($event)"
                    [module]="module" 
                    [isMaster]="isMaster"
                    [parentTestId]="parentTestId"/>
            </li>
        </ul>
    </mat-expansion-panel>
    <mat-expansion-panel [expanded]="i2cPanelOpenState" (closed)="i2cPanelOpenState = false">
        <mat-expansion-panel-header [attr.data-testId]="parentTestId + '-i2c-header'">
            <mat-panel-title>I2C configuration</mat-panel-title>
            <mat-panel-description>
                <div class="header-box">
                    <div class="header-spacer"></div>
                    <div class="header-button">
                        <button 
                            [attr.data-testId]="parentTestId + '-add-i2c'" 
                            (click)="addI2cModule($event)"
                            >
                            <fa-icon [icon]="addIcon"/>
                        </button>
                    </div>
                </div>
            </mat-panel-description>
        </mat-expansion-panel-header>
        <ul *ngIf="(location?.i2cModules)" class="i2c-list">
            <li *ngFor="let module of location.i2cModules">
                <app-i2c-module 
                    (removeModuleEvent)="removeModule($event)" 
                    (i2cAddressChangedEvent)="i2cAddressChanged($event)"
                    [updateTrigger]="i2cUpdateTrigger"
                    [module]="module" 
                    [parentTestId]="parentTestId"
                    />
            </li> 
        </ul>
    </mat-expansion-panel>
    <mat-expansion-panel>
        <mat-expansion-panel-header [attr.data-testId]="parentTestId + '-gpio-header'">
            <mat-panel-title>GPIO configuration</mat-panel-title>
        </mat-expansion-panel-header>
        <ul *ngIf="(location?.gpioModule)" class="servo-list">
            <li *ngFor="let channel of location.gpioModule.channels">
                <app-gpio-channel 
                    [channel]="channel"
                    [parentTestId]="parentTestId">
                </app-gpio-channel>
            </li>
        </ul>
    </mat-expansion-panel>
</mat-accordion>
